
# Mesh Preprocessing part
Theta1: 10.0 #first threshold for planarity
Theta2: 2.0 #second thereshold for overlapping  may not needed 


#random sampling part
point_generation_method: random_sample
Distance1: 0.5  #first threshold for distance to boundary
Distance2: 0.05 #second threshold for minimum distance between points

# display part

display_figure: true
display_points: true
display_grasp: false
attach_coordination: false

background_color: [1.0, 1.0, 1.0]
mesh_color: [0.0,0.0,0.0]  #mesh_color: [0.3529,0.1592,0.1608]
point_color: [0.8353,0.7686,0.6314]
grasp_color: [0.3059, 0.4118, 0.102]
point_size: 15

# Gripper parameters



